### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by Glagnar** [sensinov/djane#1]
I am getting an error when I run the program:
```bash
npm install
npm WARN server@1.0.0 No repository field.

audited 2472 packages in 4.669s
found 0 vulnerabilities
```
```bash 
node migrate.js
/Users/tgilbert/code/djane/node_modules/ip/lib/ip.js:370
    var res = interfaces[name].filter(function(details) {
                               ^

TypeError: Cannot read property 'filter' of undefined
    at Object.ip.address (/Users/tgilbert/code/djane/node_modules/ip/lib/ip.js:370:32)
    at Object.<anonymous> (/Users/tgilbert/code/djane/config/config.js:20:15)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/tgilbert/code/djane/migrate.js:19:16)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
```

**Comment by mbenalaya** [comment]
Thanks Glagnar. We will check this and get back to you soon.

**Comment by Alahel** [comment]
@Glagnar could you provide some info about your development platform ? Linux, MacOS ? Windows ? Thanks a lot.

**Comment by Glagnar** [comment]
Hi @Alahel I am running OSX 10.14.5 and Node version. V12.3.1 mongoldb 4.0.9.

**Comment by Glagnar** [comment]
The problem seems to have fixed itself :) I just pulled again from the repo - and now things seem to work. Thanks!
